=== OtavioESP/raw_xml_validator/xmls/stu.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="stuMessages">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="stuMessage">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="1" name="esn" type="xs:string" />
              <xs:element minOccurs="0" maxOccurs="1" name="uid" type="xs:string" />
              <xs:element minOccurs="1" maxOccurs="1" name="unixTime" type="xs:string" />
              <xs:element minOccurs="1" maxOccurs="1" name="gps" type="xs:string" />
              <xs:element minOccurs="0" maxOccurs="1" name="umn">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="15" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="payload">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="length" type="xs:int" use="required" />
                      <xs:attribute name="source" type="xs:string" use="required" />
                      <xs:attribute name="encoding" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="timeStamp" type="xs:string" use="required" />
      <xs:attribute name="messageID" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== OtavioESP/raw_xml_validator/xmls/bigstu.xml
<?xml version="1.0" encoding="UTF-8"?>
<stuMessages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="seu_caminho_aqui\stu.xsd" timeStamp="25/08/2009 21:00:00 GMT" messageID="56bdca48088610048fddba385e1cd5b8">
  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xA14AA1DBDB818F9759</payload>
  </stuMessage>

  <stuMessage>
    <esn>0-99990</esn>
    <unixTime>1034268516</unixTime>
    <gps>N</gps>
    <payload length="9" source="pc" encoding="hex">0xC0560D72DA4AB2445A</payload>
  </stuMessage>
  <stuMessage>
    <esn>0-99991</esn>
    <unixTime>1034268521</unixTime>
    <gps>N</gps>
